## which fields do we include in a dump? We leave out some fields. 

fields = {
    'a':"""fec_alerts_new_filing.committee_name as committee_name, fec_alerts_new_filing.filing_number as filing_number, fec_alerts_new_filing.form_type as form_type, formdata_skeda.form_type as line_type, superceded_by_amendment as superseded_by_amendment, filer_committee_id_number, transaction_id, back_reference_tran_id_number, back_reference_sched_name, entity_type, contributor_name, contributor_organization_name, contributor_last_name, contributor_first_name, contributor_middle_name, contributor_prefix, contributor_suffix, contributor_street_1, contributor_street_2, contributor_city, contributor_state, contributor_zip, election_code, election_other_description, contribution_date, contribution_date_formatted, contribution_amount, contribution_aggregate, contribution_purpose_code, contribution_purpose_descrip, contributor_employer, contributor_occupation, donor_committee_fec_id, donor_committee_name, donor_candidate_fec_id, donor_candidate_name, donor_candidate_last_name, donor_candidate_first_name, donor_candidate_middle_name, donor_candidate_prefix, donor_candidate_suffix, donor_candidate_office, donor_candidate_state, donor_candidate_district, conduit_name, conduit_street1, conduit_street2, conduit_city, conduit_state, conduit_zip, memo_code, memo_text_description, reference_code""",
    'b':"""fec_alerts_new_filing.committee_name as committee_name, fec_alerts_new_filing.filing_number as filing_number, fec_alerts_new_filing.form_type as form_type, formdata_skedb.form_type as line_type, superceded_by_amendment as superseded_by_amendment, filer_committee_id_number, transaction_id, back_reference_tran_id_number, back_reference_sched_name, entity_type, payee_name, payee_organization_name, payee_last_name, payee_first_name, payee_middle_name, payee_prefix, payee_suffix, payee_street_1, payee_street_2, payee_city, payee_state, payee_zip, election_code, election_other_description, expenditure_date, expenditure_date_formatted, expenditure_amount, semi_annual_refunded_bundled_amt, expenditure_purpose_code, expenditure_purpose_descrip, category_code, beneficiary_committee_fec_id, beneficiary_committee_name, beneficiary_candidate_fec_id, beneficiary_candidate_name, beneficiary_candidate_last_name, beneficiary_candidate_first_name, beneficiary_candidate_middle_name, beneficiary_candidate_prefix, beneficiary_candidate_suffix, beneficiary_candidate_office, beneficiary_candidate_state, beneficiary_candidate_district, conduit_name, conduit_street_1, conduit_street_2, conduit_city, conduit_state, conduit_zip, memo_code, memo_text_description, ref_to_sys_code_ids_acct, refund_or_disposal_of_excess, communication_date""",
    'e':"""fec_alerts_new_filing.committee_name as committee_name, fec_alerts_new_filing.filing_number as filing_number, fec_alerts_new_filing.form_type as form_type, formdata_skede.form_type as line_type, superceded_by_amendment as superseded_by_amendment, candidate_id_checked, candidate_party_checked, candidate_name_checked, candidate_office_checked, candidate_state_checked, candidate_district_checked, support_oppose_checked, fec_alerts_new_filing.committee_name, filer_committee_id_number, transaction_id, back_reference_tran_id_number, back_reference_sched_name, entity_type, payee_name, payee_organization_name, payee_last_name, payee_first_name, payee_middle_name, payee_prefix, payee_suffix, payee_street_1, payee_street_2, payee_city, payee_state, payee_zip, election_code, election_other_description, effective_date, dissemination_date, expenditure_date, expenditure_amount, calendar_y_t_d_per_election_office, expenditure_purpose_code, expenditure_purpose_descrip, category_code, payee_cmtte_fec_id_number, support_oppose_code, candidate_id_number, candidate_name, candidate_last_name, candidate_first_name, candidate_middle_name, candidate_prefix, candidate_suffix, candidate_office, candidate_state, candidate_district, completing_last_name, completing_first_name, completing_middle_name, completing_prefix, completing_suffix, date_signed, date_signed_formatted, memo_code, memo_text_description""",
    'a_date':'contribution_date_formatted',
    'b_date':'expenditure_date_formatted',
    'e_date':'effective_date',
}