import datetime

from django.core.management.base import BaseCommand, CommandError

from formdata.db_worker_settings import FIELDDIR_LOCATION

from formdata.models import *

def list_db_fields_from_model(this_model):
    """ Don't include autogenerated fields """
    field_list = []
    for field in this_model._meta.fields:
        if not field.auto_created:
            field_list.append(field.column) 
    return sorted(field_list)

class Command(BaseCommand):
    help = "Dump a hash of db fields for the data entry worker processes to read. If they import just the names, they don't need to require django"
    requires_model_validation = False

    def handle(self, *args, **options):
        
        fields = {}
        fields['A'] = list_db_fields_from_model(SkedA)
        fields['B'] = list_db_fields_from_model(SkedB)
        fields['E'] = list_db_fields_from_model(SkedE)
        fields['O'] = list_db_fields_from_model(OtherLine)
    
        timestamp = datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')
        field_def_file = open(FIELDDIR_LOCATION, 'w')
        field_def_file.write("# DB column files, autogenerated on %s\n\n" % timestamp )
        field_def_file.write("fields=%s" % str(fields))
        field_def_file.close()