# -*- coding: utf-8 -*-
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'Committee_Changed'
        db.create_table(u'formdata_committee_changed', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('committee_id', self.gf('django.db.models.fields.CharField')(max_length=9, blank=True)),
            ('time', self.gf('django.db.models.fields.DateTimeField')(auto_now=True, blank=True)),
        ))
        db.send_create_signal(u'formdata', ['Committee_Changed'])

        # Adding model 'Filing_Header'
        db.create_table(u'formdata_filing_header', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('raw_filer_id', self.gf('django.db.models.fields.CharField')(max_length=9, blank=True)),
            ('form', self.gf('django.db.models.fields.CharField')(max_length=7)),
            ('filing_number', self.gf('django.db.models.fields.IntegerField')(unique=True)),
            ('version', self.gf('django.db.models.fields.CharField')(max_length=7)),
            ('coverage_from_date', self.gf('django.db.models.fields.DateField')(null=True)),
            ('coverage_through_date', self.gf('django.db.models.fields.DateField')(null=True)),
            ('is_amendment', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('amends_filing', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('amendment_number', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('is_superceded', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('amended_by', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('covered_by_periodic_filing', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('covered_by', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('filing_time', self.gf('django.db.models.fields.DateTimeField')(null=True)),
            ('filing_time_is_exact', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('entry_complete', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('header_data', self.gf('djorm_hstore.fields.DictionaryField')(default={})),
            ('lines_present', self.gf('djorm_hstore.fields.DictionaryField')(default={}, null=True, db_index=True)),
        ))
        db.send_create_signal(u'formdata', ['Filing_Header'])

        # Adding model 'SkedA'
        db.create_table(u'formdata_skeda', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('header_id', self.gf('django.db.models.fields.IntegerField')()),
            ('filing_number', self.gf('django.db.models.fields.IntegerField')()),
            ('superceded_by_amendment', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('form_type', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('filer_committee_id_number', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('transaction_id', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('back_reference_tran_id_number', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('back_reference_sched_name', self.gf('django.db.models.fields.CharField')(max_length=8, null=True, blank=True)),
            ('entity_type', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('contributor_name', self.gf('django.db.models.fields.CharField')(max_length=200, null=True, blank=True)),
            ('contributor_organization_name', self.gf('django.db.models.fields.CharField')(max_length=200, null=True, blank=True)),
            ('contributor_last_name', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('contributor_first_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('contributor_middle_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('contributor_prefix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('contributor_suffix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('contributor_street_1', self.gf('django.db.models.fields.CharField')(max_length=34, null=True, blank=True)),
            ('contributor_street_2', self.gf('django.db.models.fields.CharField')(max_length=34, null=True, blank=True)),
            ('contributor_city', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('contributor_state', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('contributor_zip', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('election_code', self.gf('django.db.models.fields.CharField')(max_length=5, null=True, blank=True)),
            ('election_other_description', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('contribution_date', self.gf('django.db.models.fields.CharField')(max_length=8, null=True, blank=True)),
            ('contribution_date_formatted', self.gf('django.db.models.fields.DateField')(null=True)),
            ('contribution_amount', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=14, decimal_places=2)),
            ('contribution_aggregate', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=14, decimal_places=2)),
            ('contribution_purpose_code', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('contribution_purpose_descrip', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('contributor_employer', self.gf('django.db.models.fields.CharField')(max_length=38, null=True, blank=True)),
            ('contributor_occupation', self.gf('django.db.models.fields.CharField')(max_length=38, null=True, blank=True)),
            ('donor_committee_fec_id', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('donor_committee_name', self.gf('django.db.models.fields.CharField')(max_length=200, null=True, blank=True)),
            ('donor_candidate_fec_id', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('donor_candidate_name', self.gf('django.db.models.fields.CharField')(max_length=200, null=True, blank=True)),
            ('donor_candidate_last_name', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('donor_candidate_first_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('donor_candidate_middle_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('donor_candidate_prefix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('donor_candidate_suffix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('donor_candidate_office', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('donor_candidate_state', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('donor_candidate_district', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('conduit_name', self.gf('django.db.models.fields.CharField')(max_length=200, null=True, blank=True)),
            ('conduit_street1', self.gf('django.db.models.fields.CharField')(max_length=34, null=True, blank=True)),
            ('conduit_street2', self.gf('django.db.models.fields.CharField')(max_length=34, null=True, blank=True)),
            ('conduit_city', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('conduit_state', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('conduit_zip', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('memo_code', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('memo_text_description', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('reference_code', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
        ))
        db.send_create_signal(u'formdata', ['SkedA'])

        # Adding model 'SkedB'
        db.create_table(u'formdata_skedb', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('header_id', self.gf('django.db.models.fields.IntegerField')()),
            ('filing_number', self.gf('django.db.models.fields.IntegerField')()),
            ('superceded_by_amendment', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('form_type', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('filer_committee_id_number', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('transaction_id', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('back_reference_tran_id_number', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('back_reference_sched_name', self.gf('django.db.models.fields.CharField')(max_length=8, null=True, blank=True)),
            ('entity_type', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('payee_name', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('payee_organization_name', self.gf('django.db.models.fields.CharField')(max_length=200, null=True, blank=True)),
            ('payee_last_name', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('payee_first_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('payee_middle_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('payee_prefix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('payee_suffix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('payee_street_1', self.gf('django.db.models.fields.CharField')(max_length=34, null=True, blank=True)),
            ('payee_street_2', self.gf('django.db.models.fields.CharField')(max_length=34, null=True, blank=True)),
            ('payee_city', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('payee_state', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('payee_zip', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('election_code', self.gf('django.db.models.fields.CharField')(max_length=5, null=True, blank=True)),
            ('election_other_description', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('expenditure_date', self.gf('django.db.models.fields.CharField')(max_length=8, null=True, blank=True)),
            ('expenditure_date_formatted', self.gf('django.db.models.fields.DateField')(null=True)),
            ('expenditure_amount', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=14, decimal_places=2)),
            ('semi_annual_refunded_bundled_amt', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=14, decimal_places=2)),
            ('expenditure_purpose_code', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('expenditure_purpose_descrip', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('category_code', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('beneficiary_committee_fec_id', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('beneficiary_committee_name', self.gf('django.db.models.fields.CharField')(max_length=200, null=True, blank=True)),
            ('beneficiary_candidate_fec_id', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('beneficiary_candidate_name', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('beneficiary_candidate_last_name', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('beneficiary_candidate_first_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('beneficiary_candidate_middle_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('beneficiary_candidate_prefix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('beneficiary_candidate_suffix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('beneficiary_candidate_office', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('beneficiary_candidate_state', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('beneficiary_candidate_district', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('conduit_name', self.gf('django.db.models.fields.CharField')(max_length=200, null=True, blank=True)),
            ('conduit_street_1', self.gf('django.db.models.fields.CharField')(max_length=34, null=True, blank=True)),
            ('conduit_street_2', self.gf('django.db.models.fields.CharField')(max_length=34, null=True, blank=True)),
            ('conduit_city', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('conduit_state', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('conduit_zip', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('memo_code', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('memo_text_description', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('ref_to_sys_code_ids_acct', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('refund_or_disposal_of_excess', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('communication_date', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
        ))
        db.send_create_signal(u'formdata', ['SkedB'])

        # Adding model 'SkedE'
        db.create_table(u'formdata_skede', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('header_id', self.gf('django.db.models.fields.IntegerField')()),
            ('filing_number', self.gf('django.db.models.fields.IntegerField')()),
            ('superceded_by_amendment', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('form_type', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('filer_committee_id_number', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('transaction_id', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('back_reference_tran_id_number', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('back_reference_sched_name', self.gf('django.db.models.fields.CharField')(max_length=8, null=True, blank=True)),
            ('entity_type', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('payee_name', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('payee_organization_name', self.gf('django.db.models.fields.CharField')(max_length=200, null=True, blank=True)),
            ('payee_last_name', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('payee_first_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('payee_middle_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('payee_prefix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('payee_suffix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('payee_street_1', self.gf('django.db.models.fields.CharField')(max_length=34, null=True, blank=True)),
            ('payee_street_2', self.gf('django.db.models.fields.CharField')(max_length=34, null=True, blank=True)),
            ('payee_city', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('payee_state', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('payee_zip', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('election_code', self.gf('django.db.models.fields.CharField')(max_length=5, null=True, blank=True)),
            ('election_other_description', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('expenditure_date', self.gf('django.db.models.fields.CharField')(max_length=8, null=True, blank=True)),
            ('expenditure_date_formatted', self.gf('django.db.models.fields.DateField')(null=True)),
            ('expenditure_amount', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=14, decimal_places=2)),
            ('calendar_y_t_d_per_election_office', self.gf('django.db.models.fields.DecimalField')(null=True, max_digits=14, decimal_places=2)),
            ('expenditure_purpose_code', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('expenditure_purpose_descrip', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('category_code', self.gf('django.db.models.fields.CharField')(max_length=3, null=True, blank=True)),
            ('payee_cmtte_fec_id_number', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('support_oppose_code', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('candidate_id_number', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('candidate_name', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
            ('candidate_last_name', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('candidate_first_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('candidate_middle_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('candidate_prefix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('candidate_suffix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('candidate_office', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('candidate_state', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('candidate_district', self.gf('django.db.models.fields.CharField')(max_length=2, null=True, blank=True)),
            ('completing_last_name', self.gf('django.db.models.fields.CharField')(max_length=30, null=True, blank=True)),
            ('completing_first_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('completing_middle_name', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('completing_prefix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('completing_suffix', self.gf('django.db.models.fields.CharField')(max_length=10, null=True, blank=True)),
            ('date_signed', self.gf('django.db.models.fields.CharField')(max_length=8, null=True, blank=True)),
            ('date_signed_formatted', self.gf('django.db.models.fields.DateField')(null=True)),
            ('memo_code', self.gf('django.db.models.fields.CharField')(max_length=1, null=True, blank=True)),
            ('memo_text_description', self.gf('django.db.models.fields.CharField')(max_length=100, null=True, blank=True)),
        ))
        db.send_create_signal(u'formdata', ['SkedE'])

        # Adding model 'OtherLine'
        db.create_table(u'formdata_otherline', (
            (u'id', self.gf('django.db.models.fields.AutoField')(primary_key=True)),
            ('header_id', self.gf('django.db.models.fields.IntegerField')()),
            ('filing_number', self.gf('django.db.models.fields.IntegerField')()),
            ('superceded_by_amendment', self.gf('django.db.models.fields.BooleanField')(default=False)),
            ('form_parser', self.gf('django.db.models.fields.CharField')(max_length=6, blank=True)),
            ('form_type', self.gf('django.db.models.fields.CharField')(max_length=8, blank=True)),
            ('filer_committee_id_number', self.gf('django.db.models.fields.CharField')(max_length=9, null=True, blank=True)),
            ('transaction_id', self.gf('django.db.models.fields.CharField')(max_length=20, null=True, blank=True)),
            ('line_data', self.gf('djorm_hstore.fields.DictionaryField')(default={}, null=True)),
        ))
        db.send_create_signal(u'formdata', ['OtherLine'])


    def backwards(self, orm):
        # Deleting model 'Committee_Changed'
        db.delete_table(u'formdata_committee_changed')

        # Deleting model 'Filing_Header'
        db.delete_table(u'formdata_filing_header')

        # Deleting model 'SkedA'
        db.delete_table(u'formdata_skeda')

        # Deleting model 'SkedB'
        db.delete_table(u'formdata_skedb')

        # Deleting model 'SkedE'
        db.delete_table(u'formdata_skede')

        # Deleting model 'OtherLine'
        db.delete_table(u'formdata_otherline')


    models = {
        u'formdata.committee_changed': {
            'Meta': {'object_name': 'Committee_Changed'},
            'committee_id': ('django.db.models.fields.CharField', [], {'max_length': '9', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'time': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'})
        },
        u'formdata.filing_header': {
            'Meta': {'object_name': 'Filing_Header'},
            'amended_by': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'amendment_number': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'amends_filing': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'coverage_from_date': ('django.db.models.fields.DateField', [], {'null': 'True'}),
            'coverage_through_date': ('django.db.models.fields.DateField', [], {'null': 'True'}),
            'covered_by': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'covered_by_periodic_filing': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'entry_complete': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'filing_number': ('django.db.models.fields.IntegerField', [], {'unique': 'True'}),
            'filing_time': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'filing_time_is_exact': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'form': ('django.db.models.fields.CharField', [], {'max_length': '7'}),
            'header_data': ('djorm_hstore.fields.DictionaryField', [], {'default': '{}'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_amendment': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superceded': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'lines_present': ('djorm_hstore.fields.DictionaryField', [], {'default': '{}', 'null': 'True', 'db_index': 'True'}),
            'raw_filer_id': ('django.db.models.fields.CharField', [], {'max_length': '9', 'blank': 'True'}),
            'version': ('django.db.models.fields.CharField', [], {'max_length': '7'})
        },
        u'formdata.otherline': {
            'Meta': {'object_name': 'OtherLine'},
            'filer_committee_id_number': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'filing_number': ('django.db.models.fields.IntegerField', [], {}),
            'form_parser': ('django.db.models.fields.CharField', [], {'max_length': '6', 'blank': 'True'}),
            'form_type': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'header_id': ('django.db.models.fields.IntegerField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'line_data': ('djorm_hstore.fields.DictionaryField', [], {'default': '{}', 'null': 'True'}),
            'superceded_by_amendment': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transaction_id': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'})
        },
        u'formdata.skeda': {
            'Meta': {'object_name': 'SkedA'},
            'back_reference_sched_name': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'back_reference_tran_id_number': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'conduit_city': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'conduit_name': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'conduit_state': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'conduit_street1': ('django.db.models.fields.CharField', [], {'max_length': '34', 'null': 'True', 'blank': 'True'}),
            'conduit_street2': ('django.db.models.fields.CharField', [], {'max_length': '34', 'null': 'True', 'blank': 'True'}),
            'conduit_zip': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'contribution_aggregate': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '14', 'decimal_places': '2'}),
            'contribution_amount': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '14', 'decimal_places': '2'}),
            'contribution_date': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'contribution_date_formatted': ('django.db.models.fields.DateField', [], {'null': 'True'}),
            'contribution_purpose_code': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'contribution_purpose_descrip': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'contributor_city': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'contributor_employer': ('django.db.models.fields.CharField', [], {'max_length': '38', 'null': 'True', 'blank': 'True'}),
            'contributor_first_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'contributor_last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'contributor_middle_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'contributor_name': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'contributor_occupation': ('django.db.models.fields.CharField', [], {'max_length': '38', 'null': 'True', 'blank': 'True'}),
            'contributor_organization_name': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'contributor_prefix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'contributor_state': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'contributor_street_1': ('django.db.models.fields.CharField', [], {'max_length': '34', 'null': 'True', 'blank': 'True'}),
            'contributor_street_2': ('django.db.models.fields.CharField', [], {'max_length': '34', 'null': 'True', 'blank': 'True'}),
            'contributor_suffix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'contributor_zip': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'donor_candidate_district': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'donor_candidate_fec_id': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'donor_candidate_first_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'donor_candidate_last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'donor_candidate_middle_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'donor_candidate_name': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'donor_candidate_office': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'donor_candidate_prefix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'donor_candidate_state': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'donor_candidate_suffix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'donor_committee_fec_id': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'donor_committee_name': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'election_code': ('django.db.models.fields.CharField', [], {'max_length': '5', 'null': 'True', 'blank': 'True'}),
            'election_other_description': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'entity_type': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'filer_committee_id_number': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'filing_number': ('django.db.models.fields.IntegerField', [], {}),
            'form_type': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'header_id': ('django.db.models.fields.IntegerField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'memo_code': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'memo_text_description': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'reference_code': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'superceded_by_amendment': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transaction_id': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'})
        },
        u'formdata.skedb': {
            'Meta': {'object_name': 'SkedB'},
            'back_reference_sched_name': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'back_reference_tran_id_number': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'beneficiary_candidate_district': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'beneficiary_candidate_fec_id': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'beneficiary_candidate_first_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'beneficiary_candidate_last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'beneficiary_candidate_middle_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'beneficiary_candidate_name': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'beneficiary_candidate_office': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'beneficiary_candidate_prefix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'beneficiary_candidate_state': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'beneficiary_candidate_suffix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'beneficiary_committee_fec_id': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'beneficiary_committee_name': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'category_code': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'communication_date': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'conduit_city': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'conduit_name': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'conduit_state': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'conduit_street_1': ('django.db.models.fields.CharField', [], {'max_length': '34', 'null': 'True', 'blank': 'True'}),
            'conduit_street_2': ('django.db.models.fields.CharField', [], {'max_length': '34', 'null': 'True', 'blank': 'True'}),
            'conduit_zip': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'election_code': ('django.db.models.fields.CharField', [], {'max_length': '5', 'null': 'True', 'blank': 'True'}),
            'election_other_description': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'entity_type': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'expenditure_amount': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '14', 'decimal_places': '2'}),
            'expenditure_date': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'expenditure_date_formatted': ('django.db.models.fields.DateField', [], {'null': 'True'}),
            'expenditure_purpose_code': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'expenditure_purpose_descrip': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'filer_committee_id_number': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'filing_number': ('django.db.models.fields.IntegerField', [], {}),
            'form_type': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'header_id': ('django.db.models.fields.IntegerField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'memo_code': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'memo_text_description': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'payee_city': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'payee_first_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'payee_last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'payee_middle_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'payee_name': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'payee_organization_name': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'payee_prefix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'payee_state': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'payee_street_1': ('django.db.models.fields.CharField', [], {'max_length': '34', 'null': 'True', 'blank': 'True'}),
            'payee_street_2': ('django.db.models.fields.CharField', [], {'max_length': '34', 'null': 'True', 'blank': 'True'}),
            'payee_suffix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'payee_zip': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'ref_to_sys_code_ids_acct': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'refund_or_disposal_of_excess': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'semi_annual_refunded_bundled_amt': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '14', 'decimal_places': '2'}),
            'superceded_by_amendment': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'transaction_id': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'})
        },
        u'formdata.skede': {
            'Meta': {'object_name': 'SkedE'},
            'back_reference_sched_name': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'back_reference_tran_id_number': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'calendar_y_t_d_per_election_office': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '14', 'decimal_places': '2'}),
            'candidate_district': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'candidate_first_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'candidate_id_number': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'candidate_last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'candidate_middle_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'candidate_name': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'candidate_office': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'candidate_prefix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'candidate_state': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'candidate_suffix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'category_code': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'completing_first_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'completing_last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'completing_middle_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'completing_prefix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'completing_suffix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'date_signed': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'date_signed_formatted': ('django.db.models.fields.DateField', [], {'null': 'True'}),
            'election_code': ('django.db.models.fields.CharField', [], {'max_length': '5', 'null': 'True', 'blank': 'True'}),
            'election_other_description': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'entity_type': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'expenditure_amount': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '14', 'decimal_places': '2'}),
            'expenditure_date': ('django.db.models.fields.CharField', [], {'max_length': '8', 'null': 'True', 'blank': 'True'}),
            'expenditure_date_formatted': ('django.db.models.fields.DateField', [], {'null': 'True'}),
            'expenditure_purpose_code': ('django.db.models.fields.CharField', [], {'max_length': '3', 'null': 'True', 'blank': 'True'}),
            'expenditure_purpose_descrip': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'filer_committee_id_number': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'filing_number': ('django.db.models.fields.IntegerField', [], {}),
            'form_type': ('django.db.models.fields.CharField', [], {'max_length': '8', 'blank': 'True'}),
            'header_id': ('django.db.models.fields.IntegerField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'memo_code': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'memo_text_description': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'payee_city': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'payee_cmtte_fec_id_number': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'payee_first_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'payee_last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'null': 'True', 'blank': 'True'}),
            'payee_middle_name': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'}),
            'payee_name': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'payee_organization_name': ('django.db.models.fields.CharField', [], {'max_length': '200', 'null': 'True', 'blank': 'True'}),
            'payee_prefix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'payee_state': ('django.db.models.fields.CharField', [], {'max_length': '2', 'null': 'True', 'blank': 'True'}),
            'payee_street_1': ('django.db.models.fields.CharField', [], {'max_length': '34', 'null': 'True', 'blank': 'True'}),
            'payee_street_2': ('django.db.models.fields.CharField', [], {'max_length': '34', 'null': 'True', 'blank': 'True'}),
            'payee_suffix': ('django.db.models.fields.CharField', [], {'max_length': '10', 'null': 'True', 'blank': 'True'}),
            'payee_zip': ('django.db.models.fields.CharField', [], {'max_length': '9', 'null': 'True', 'blank': 'True'}),
            'superceded_by_amendment': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'support_oppose_code': ('django.db.models.fields.CharField', [], {'max_length': '1', 'null': 'True', 'blank': 'True'}),
            'transaction_id': ('django.db.models.fields.CharField', [], {'max_length': '20', 'null': 'True', 'blank': 'True'})
        }
    }

    complete_apps = ['formdata']